spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: qwe123
    driver-class-name: org.postgresql.Driver


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      database-call:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      database-call:
        timeoutDuration: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always